layout_spectrum: 0.4982079
typography_spectrum: 0.3512545
color:
  saturation: 0.1713112
  lightness: 0.4264278
  brandStrength: 0.7066846
  rhythmicContrast: 0.6804836
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Columba
